# Generated by Django 4.0.4 on 2022-05-26 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latlang',
            field=models.CharField(default='Location Not Found', max_length=30),
        ),
    ]
