# Generated by Django 4.0.4 on 2022-05-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_latlang_location_latlong'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='time',
            field=models.CharField(default='00:00:00', max_length=30),
        ),
        migrations.AlterField(
            model_name='location',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='latlong',
            field=models.CharField(default='Location Not Found', max_length=100),
        ),
        migrations.AlterField(
            model_name='location',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
