# Generated by Django 4.0.4 on 2022-05-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_location_time_alter_location_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logindetails',
            name='phoneNumber',
            field=models.CharField(max_length=20),
        ),
    ]
